#!/usr/bin/env bash

set -e

# Install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install wget
brew install wget

# Install iTerm2
brew cask install iterm2

# Install tmux
brew install tmux

# Install node
brew install node

# Install htop
brew install htop

# Install tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Install coreutils
brew install coreutils

# Install cowsay
brew install cowsay

# Install fortune
brew install fortune

# Install dircolors
git clone https://github.com/seebi/dircolors-solarized ~/.dircolors

# Create backup of .zshrc
cp ~/.zshrc ~/.zshrctmp

# Install zsh
brew install zsh

# Install oh-my-zsh
wget --no-check-certificate https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
RUNZSH=no sh install.sh
rm install.sh
rm ~/.zshrc && mv ~/.zshrctmp ~/.zshrc
mv agnoster_vi.zsh-theme ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes

# Install dracula for zsh
git clone https://github.com/dracula/zsh.git ~/.dracula_zsh
mv .dracula_zsh/* ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes
rf -rf .dracula_zsh

# Install solarized theme
wget --no-check-certificate -O ~/.dircolors/solarized-iterm https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Solarized%20Dark%20-%20Patched.itermcolors

# Download powerline font
wget --no-check-certificate -O ~/Library/Fonts/source_code_for_powerline.otf https://github.com/powerline/fonts/raw/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf

# Install syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Install auto suggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install emoji cli
brew install jq fzf peco && git clone https://github.com/b4b4r07/emoji-cli ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/emoji-cli

# Install macvim
brew install cmake macvim

# Install coc.nvim
mkdir -p ~/.vim/pack/coc/start
cd ~/.vim/pack/coc/start
curl --fail -L https://github.com/neoclide/coc.nvim/archive/release.tar.gz | tar xzfv -
cd ~

# Install vim-javascript
git clone https://github.com/pangloss/vim-javascript.git ~/.vim/pack/vim-javascript/start/vim-javascript

# Install haskell-vim
git clone https://github.com/neovimhaskell/haskell-vim.git ~/.vim/bundle/haskell-vim

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install vim plugins
vim +PluginInstall +qall

# Install vim-

# Install vim solarized colors
git clone https://github.com/altercation/vim-colors-solarized
mkdir -p ~/.vim/colors/
mv vim-colors-solarized/colors/solarized.vim ~/.vim/colors/
rm -rf vim-colors-solarized

# Move files
sudo mv ~/tmux-split /usr/local/bin/tmux-split
